### PR TITLE
Visualize pitch bend has no response to [CC 151]Pitch bend sensitivity! Please fix! 

### PR DESCRIPTION
**Pull request by happymimimix**
IDK if this is the right place to ask this. 
Please fix this problem with visualize pitch bend ASAP! 

Also, may I ask you to add a rotation function to the piano roll? 
And an option to let visualize pitch bend matching tracks instead of channels please! 

I want to add pitch bend to my note arts and make them move horizontally to create some special visual effects. 
But 16 channels are way less than enough for that. 
Can you add an option to make visualize pitch bend apply to individual tracks instead of channels? 

Also, I want a pianoroll rotate function like the one shown below: 
image

to create some special visual effects. 
Can you make one for me if possible?

### CODE REVIEW

**Comment by khang06** [comment]
not sure why issues weren't enabled on this repo. should be fixed now

making pitch bends match the sensitivity shouldn't be too hard, i'll do that eventually

pitch bending tracks would be difficult to do without increasing memory usage because it would require every midi channel event to keep track of what track it's on, so i don't think i'll implement that. in theory it shouldn't be hard and should just involve changing the size of the bends array in the shader and renderer along with making it read track instead of channel

piano roll rotation should be possible by modifying the projection matrix [here](https://github.com/khang06/PianoFromAbove/blob/468b38492be23c1492d2e8c4833739c7cac2a8cb/PianoFromAbove/Renderer.cpp#L847) but i'm not sure how useful that would be to most people since it's usually done in video editing. there would mainly be issues with ensuring notes get properly clipped and trying to expose it in a reasonable way in the ui

**Comment by happymimimix** [comment]
> not sure why issues weren't enabled on this repo. should be fixed now
> 
> making pitch bends match the sensitivity shouldn't be too hard, i'll do that eventually
> 
> pitch bending tracks would be difficult to do without increasing memory usage because it would require every midi channel event to keep track of what track it's on, so i don't think i'll implement that. in theory it shouldn't be hard and should just involve changing the size of the bends array in the shader and renderer along with making it read track instead of channel
> 
> piano roll rotation should be possible by modifying the projection matrix [here](https://github.com/khang06/PianoFromAbove/blob/468b38492be23c1492d2e8c4833739c7cac2a8cb/PianoFromAbove/Renderer.cpp#L847) but i'm not sure how useful that would be to most people since it's usually done in video editing. there would mainly be issues with ensuring notes get properly clipped and trying to expose it in a reasonable way in the ui

I know that make pitch bends matching tracks could increase memory usage, that's why I want it to be added as an option that the user can choose. 
Selecting it will pop up a warning that says more memory may be used. 
The option will apply the next time the user loads a midi file. 
And the option is off by default. 

I know that piano roll rotation could be done with video editing, but that's video editing eventually. 
I want the whole thing to be played in real time! with visualize pitch bend and piano roll rotation effect. 
I already found a way to modify the value in memory with an external program. 
And I'm now making a tool called VIZ-Animator, allowing user to specify the movements of the piano at specific time. 
Then the values in the memory will be changed to the target value as the midi plays. 
The best thing about this is that it happens real-time! 
No video edit! 

Thanks for your help pointing our that matrix that could be used to do piano roll rotation, this helped a lot! 

Umm...
May I ask you another thing: 
When I change the playback speed to a negative value with cheat engine, can you let the music play backwards? 
And the note speed as well, make the notes fly upwards instead of just disappear with negative note speed. 
I want to use this to create special visual effects in my black midi, and I want this to happen real-time. No video edit! 


The way that I'm going to use these features is: 
Open cheat engine and press Ctrl + Alt + L
Paste the following lua script inside: 
```
TME = "PFAVIZMODDED_v2.1.6.exe+1E12E0"
PBS = "PFAVIZMODDED_v2.1.6.exe+1E1178"
NTS = "PFAVIZMODDED_v2.1.6.exe+1E1180"
PBV = "PFAVIZMODDED_v2.1.6.exe+1E1188"
ZOM = "PFAVIZMODDED_v2.1.6.exe+1E11A8"
MVX = "PFAVIZMODDED_v2.1.6.exe+1E11A0"
MVY = "PFAVIZMODDED_v2.1.6.exe+1E11A4"
KBD = "PFAVIZMODDED_v2.1.6.exe+1E119A"
function RTME()
return readDouble(TME)
end
function RPBS()
return readDouble(PBS)
end
function RNTS()
return readDouble(NTS)
end
function RPBV()
return readDouble(PBV)
end
function RZOM()
return readFloat(ZOM)
end
function RMVX()
return readFloat(MVX)
end
function RMVY()
return readFloat(MVY)
end
function RKBD()
return readByte(KBD)
end
function WTME(VAL)
writeDouble(TME,VAL)
end
function WPBS(VAL)
writeDouble(PBS,VAL)
end
function WNTS(VAL)
writeDouble(NTS,VAL)
end
function WPBV(VAL)
writeDouble(PBV,VAL)
end
function WZOM(VAL)
writeFloat(ZOM,VAL)
end
function WMVX(VAL)
writeFloat(MVX,VAL)
end
function WMVY(VAL)
writeFloat(MVY,VAL)
end
function KBDO()
writeByte(KBD,0)
end
function KBDI()
writeByte(KBD,1)
end
function KBDT()
if (RKBD() == 1)then
writeByte(KBD,0)
end
if (RKBD() == 0)then
writeByte(KBD,1)
end
end
function WIT(TRM)
while (RTME() < TRM) do
end
end
```

Then, write
```
WIT(23123)
WMVX(500)
```
will let the piano roll move right for 500 pixels at 23123 microseconds.

**Comment by happymimimix** [comment]
> not sure why issues weren't enabled on this repo. should be fixed now
> 
> making pitch bends match the sensitivity shouldn't be too hard, i'll do that eventually
> 
> pitch bending tracks would be difficult to do without increasing memory usage because it would require every midi channel event to keep track of what track it's on, so i don't think i'll implement that. in theory it shouldn't be hard and should just involve changing the size of the bends array in the shader and renderer along with making it read track instead of channel
> 
> piano roll rotation should be possible by modifying the projection matrix [here](https://github.com/khang06/PianoFromAbove/blob/468b38492be23c1492d2e8c4833739c7cac2a8cb/PianoFromAbove/Renderer.cpp#L847) but i'm not sure how useful that would be to most people since it's usually done in video editing. there would mainly be issues with ensuring notes get properly clipped and trying to expose it in a reasonable way in the ui

[VIZ-Animator internal beta build 1384.zip](https://github.com/khang06/PianoFromAbove/files/11562530/VIZ-Animator.internal.beta.build.1384.zip)
Here is the incomplete source code of my VIZ-Animator. 

If you do all animations by editing the lua script strait away, then you have to write: 
```
WIT(23123)
WMVX(5)
WIT(23133)
WMVX(10)
WIT(23143)
WMVX(15)
WIT(23153)
WMVX(20)
WIT(23163)
WMVX(25)
WIT(23173)
WMVX(30)
WIT(23183)
WMVX(35)
WIT(23193)
WMVX(40)
WIT(23203)
WMVX(45)
WIT(23213)
WMVX(50)
```
to let the piano do a smooth move to the right for 50 pixels in 0.1 seconds. 
Which is very complicated. 

The job of VIZ-Animator is to simplify the process to simply clicking mouse buttons! 
And all those scripts will be generated automatically! 

My programming knowledge is enough to create this simple tool, but I need your help to add support to PianoFromAbove VIZ. 
Once PianoFromAbove supports piano roll rotation through memory injection, it's easy for me to add support for that in my VIZ Animator. 
Since it's just simply search for the memory address for rotation and add a new event type called rotation in my program.

**Comment by happymimimix** [comment]
> > not sure why issues weren't enabled on this repo. should be fixed now
> > making pitch bends match the sensitivity shouldn't be too hard, i'll do that eventually
> > pitch bending tracks would be difficult to do without increasing memory usage because it would require every midi channel event to keep track of what track it's on, so i don't think i'll implement that. in theory it shouldn't be hard and should just involve changing the size of the bends array in the shader and renderer along with making it read track instead of channel
> > piano roll rotation should be possible by modifying the projection matrix [here](https://github.com/khang06/PianoFromAbove/blob/468b38492be23c1492d2e8c4833739c7cac2a8cb/PianoFromAbove/Renderer.cpp#L847) but i'm not sure how useful that would be to most people since it's usually done in video editing. there would mainly be issues with ensuring notes get properly clipped and trying to expose it in a reasonable way in the ui
> 
> I know that make pitch bends matching tracks could increase memory usage, that's why I want it to be added as an option that the user can choose. Selecting it will pop up a warning that says more memory may be used. The option will apply the next time the user loads a midi file. And the option is off by default.
> 
> I know that piano roll rotation could be done with video editing, but that's video editing eventually. I want the whole thing to be played in real time! with visualize pitch bend and piano roll rotation effect. I already found a way to modify the value in memory with an external program. And I'm now making a tool called VIZ-Animator, allowing user to specify the movements of the piano at specific time. Then the values in the memory will be changed to the target value as the midi plays. The best thing about this is that it happens real-time! No video edit!
> 
> Thanks for your help pointing our that matrix that could be used to do piano roll rotation, this helped a lot!
> 
> Umm... May I ask you another thing: When I change the playback speed to a negative value with cheat engine, can you let the music play backwards? And the note speed as well, make the notes fly upwards instead of just disappear with negative note speed. I want to use this to create special visual effects in my black midi, and I want this to happen real-time. No video edit!
> 
> The way that I'm going to use these features is: Open cheat engine and press Ctrl + Alt + L Paste the following lua script inside:
> 
> ```
> TME = "PFAVIZMODDED_v2.1.6.exe+1E12E0"
> PBS = "PFAVIZMODDED_v2.1.6.exe+1E1178"
> NTS = "PFAVIZMODDED_v2.1.6.exe+1E1180"
> PBV = "PFAVIZMODDED_v2.1.6.exe+1E1188"
> ZOM = "PFAVIZMODDED_v2.1.6.exe+1E11A8"
> MVX = "PFAVIZMODDED_v2.1.6.exe+1E11A0"
> MVY = "PFAVIZMODDED_v2.1.6.exe+1E11A4"
> KBD = "PFAVIZMODDED_v2.1.6.exe+1E119A"
> function RTME()
> return readDouble(TME)
> end
> function RPBS()
> return readDouble(PBS)
> end
> function RNTS()
> return readDouble(NTS)
> end
> function RPBV()
> return readDouble(PBV)
> end
> function RZOM()
> return readFloat(ZOM)
> end
> function RMVX()
> return readFloat(MVX)
> end
> function RMVY()
> return readFloat(MVY)
> end
> function RKBD()
> return readByte(KBD)
> end
> function WTME(VAL)
> writeDouble(TME,VAL)
> end
> function WPBS(VAL)
> writeDouble(PBS,VAL)
> end
> function WNTS(VAL)
> writeDouble(NTS,VAL)
> end
> function WPBV(VAL)
> writeDouble(PBV,VAL)
> end
> function WZOM(VAL)
> writeFloat(ZOM,VAL)
> end
> function WMVX(VAL)
> writeFloat(MVX,VAL)
> end
> function WMVY(VAL)
> writeFloat(MVY,VAL)
> end
> function KBDO()
> writeByte(KBD,0)
> end
> function KBDI()
> writeByte(KBD,1)
> end
> function KBDT()
> if (RKBD() == 1)then
> writeByte(KBD,0)
> end
> if (RKBD() == 0)then
> writeByte(KBD,1)
> end
> end
> function WIT(TRM)
> while (RTME() < TRM) do
> end
> end
> ```
> 
> Then, write
> 
> ```
> WIT(23123)
> WMVX(500)
> ```
> 
> will let the piano roll move right for 500 pixels at 23123 microseconds.

Oh, another note for that lua script. 
For this address: TME = "PFAVIZMODDED_v2.1.6.exe+1E12E0"
You need my mod of PianoFromAbove VIZ, this memory address does not exist in yours. 
https://github.com/sudo-000/PianoFromAboveVIZ-modded

**Pull request closed without merging**
